export interface Expense {
  id?: number; // auto-generated by IndexedDB
  amount: number;
  category: string;
  date: string; // ISO string e.g. "2026-03-06"
  note?: string;
}

export interface Budget {
  id: 1; // always 1 (only one budget record)
  monthlyLimit: number; 
}

export interface Category {
  name: string;
  categoryBudget?: number; 
}

